name: "Continuous Integration"

on: [push, pull_request]

jobs:
  analyze:
    name: 
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python all python version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
     - name: Install dependencies
       run: python setup.py install
     - name: Run pytest
       run: pytest