name: "Continuous Integration"

on: [push, pull_request]

jobs:
  test:
    name: Unit tests 
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    # Setup Python (faster than using Python container)
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install solid
      run: python setup.py install
    - name: Install pytest
      run: pip install pytest
    - name: Run pytest
      run: pytest

